
default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['pg_host'] %>
  port: <%= ENV['pg_port'] %>
  username: <%= ENV['pg_user'] %>
  password: <%= ENV['pg_password'] %>

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: registros_development
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['pg_host'] %>
  port: <%= ENV['pg_port'] %>
  username: <%= ENV['pg_user'] %>
  password: <%= ENV['pg_password'] %>

production:
  <<: *default
  database: registros_production
  username: registros
  password: <%= ENV['REGISTROS_DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: registros_test
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['pg_host'] %>
  port: <%= ENV['pg_port'] %>
  username: <%= ENV['pg_user'] %>
  password: <%= ENV['pg_password'] %>
